
package sesion36martinezed_cola1;

import javax.swing.JOptionPane;

/**
 *
 * @author capri
 */
public class TestOperacionesColas extends javax.swing.JFrame {

    OperacionesCola cola = new OperacionesCola(5);
    public TestOperacionesColas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnAñadirElmentosCola = new javax.swing.JButton();
        btnImprimirElementos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("Oeraciones ED colas Martiez");

        btnAñadirElmentosCola.setText("Realizar cola elementos en ED ");
        btnAñadirElmentosCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirElmentosColaActionPerformed(evt);
            }
        });

        btnImprimirElementos.setText("Imprimir elemtos en ED cola");
        btnImprimirElementos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirElementosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnImprimirElementos)
                            .addComponent(btnAñadirElmentosCola))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblTitulo)
                .addGap(33, 33, 33)
                .addComponent(btnAñadirElmentosCola)
                .addGap(51, 51, 51)
                .addComponent(btnImprimirElementos)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirElmentosColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirElmentosColaActionPerformed
           for (int i = 0; i <=5; i++) {
               try {
                   cola.insertar(i);
                   JOptionPane.showMessageDialog(null, "Llenando Valores \n"+(i+1));
               } catch (Exception e) {
                   JOptionPane.showMessageDialog(null, "Error  Al Insertar Los Datos\n"+e);
                   
               }
            
        }
    }//GEN-LAST:event_btnAñadirElmentosColaActionPerformed

    private void btnImprimirElementosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirElementosActionPerformed
       
                cola.imprimir();
                JOptionPane.showMessageDialog(null, "Cola Llena De Valores Es \nTamaño Maximio Es :\n "+cola.tamMax());
        
    }//GEN-LAST:event_btnImprimirElementosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestOperacionesColas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestOperacionesColas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestOperacionesColas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestOperacionesColas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestOperacionesColas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadirElmentosCola;
    private javax.swing.JButton btnImprimirElementos;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
