
package sesion5edpilas;

import java.util.Stack;
import javax.swing.JOptionPane;


/**
 *
 * @author capri
 */

public class TestLibroPila extends javax.swing.JFrame {
   
    //Declaracion de pila Libnros
           Stack<Libro>  pila= new Stack<Libro>(); 
            Libro libro1 = new Libro("Caprii", "Estructura de Datos", 2002, "UACM");
            Libro libro2 = new Libro("Caprii", "C++", 2001, "BACHILLERES");
            Libro libro3 = new Libro("Caprii", "JAVA", 2010, "CETIS");
            Libro libro4 = new Libro("Caprii", "PHYTON", 2020, "CONALEP");
            Libro libro5 = new Libro("Caprii", "C", 2089, "UNAM");
           
                   
            
            
            

    
    public TestLibroPila() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnConsulta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("Operaciones Libros Biblioteca Martinez");

        btnConsulta.setText("Consultar Libros");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(lblTitulo)
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConsulta)
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblTitulo)
                .addGap(40, 40, 40)
                .addComponent(btnConsulta)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
           //Agregando informacion de libros
           pila.push(libro1);     
           pila.push(libro2);
           pila.push(libro3);
           pila.push(libro4);
           pila.push(libro5);
           
          // JOptionPane.showMessageDialog(null, pila);
         /* for (Libro libro : pila) {
            
        
           JOptionPane.showInternalMessageDialog(null, "Datos De Libro"
                                                                                         + "\nAutor:  "+pila.peek().getAutor()
                                                                                         +"\nTitulo:  "+pila.peek().getTitulo()
                                                                                         +"\nFecha De Publicacion:  "+pila.peek().getAni()
                                                                                         +"\nEditorial:  "+pila.peek().getEditorial() );
          }*/
          while (! pila.isEmpty() ) { //Inicia whiele
               
              JOptionPane.showInternalMessageDialog(null, "Datos De Libro"
                                                                                         + "\nAutor:  "+pila.peek().getAutor()
                                                                                         +"\nTitulo:  "+pila.peek().getTitulo()
                                                                                         +"\nFecha De Publicacion:  "+pila.peek().getAni()
                                                                                         +"\nEditorial:  "+pila.peek().getEditorial() );
              pila.pop();//ultimo elemento de la pila
            
        }
          
          // System.err.println("La Pila Es La Siguiente "+libro1);
           
    }//GEN-LAST:event_btnConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestLibroPila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestLibroPila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestLibroPila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestLibroPila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestLibroPila().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsulta;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
